### ISSUE TITLE
Endpoint Data

### ISSUE THREAD

**Issue by paytonalexanderwhipple** [devmtngrouprpn/notStackOverflow#13]
The get endpoint for /home needs the following pieces of data.
- an array of tags associated with the question right now each tag has its own question.
- a boolean indicating if he question has an accepted answer.
- the reputation of the user who posted the question.

**Comment by HGIRyan** [comment]
Reputation was already there you blind bat.
added boolean for accepted answer.
created algorithm to filter through and sort the tags.
